### ISSUE TITLE
Manage remote node using command line parameter

### ISSUE THREAD

**Issue by amunoz951** [mhedgpeth/cafe#5]
Having the ability to specify the node to be managed via command line would greatly improve ease of use. 

Example:
cafe chef pause -s myMachine01

**Comment by mhedgpeth** [comment]
Great idea @amunoz951 I've been working on it this week & will get it completed soon.

**Comment by mhedgpeth** [comment]
Added PR #9 to address this. Instead of `-s` I'm using `on:` as a way of determining this. Will do further testing and then merge it. This will be a part of a release with this and other elements.

**Comment by mhedgpeth** [comment]
This is ready to go. I found it difficult to get windows to open its firewalls/etc. over the line to allow the communication, but the application will attempt http on the specified port when you add "on: servername" to it.
