### ISSUE TITLE
Ability to run 'cafe chef run' manually while chef is paused

### ISSUE THREAD

**Issue by finam** [mhedgpeth/cafe#7]
**use case:** 
chef is paused on a node, we want to run chef-client once, but still remain in the paused state
-deploying monolithic application, debugging purposes

**desired use:**
```
cafe chef pause
cafe chef run
--currently throws exception
```

**current use:**
```
cafe chef pause
cafe chef resume
cafe chef run
cafe chef pause
--2 extra commands and possibility of chef run being scheduled before running it manually
```

**Comment by mhedgpeth** [comment]
I tested this out tonight and you should be able to run chef while it is paused. Please try it and reopen the issue if you see otherwise with a specific example. Thanks!
